<?php

/**
 * Define module root directory.
 */
define('ODP_API', dirname(__FILE__));

/**
 * Include API files.
 */
require_once ODP_API . '/includes/constants.inc';
require_once ODP_API . '/includes/model.inc';
require_once ODP_API . '/includes/controller.inc';

/**
 * Implements hook_menu().
 */
function odp_api_menu() {
  // Init output variable.
  $items = array();

  $items['api/json'] = array(
    'title' => 'Api',
    'page callback' => 'odp_api_page',
    'access callback' => 'odp_api_access',
    'delivery callback' => 'odp_api_json_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages/api.inc',
  );
  $items['api/xml'] = array(
    'title' => 'Api',
    'page callback' => 'odp_api_page',
    'access callback' => 'odp_api_access',
    'delivery callback' => 'odp_api_xml_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages/api.inc',
  );
  $items['api'] = $items['api/json'];

  return $items;
}

/**
 * Access callback.
 */
function odp_api_access() {
  $get = drupal_get_query_parameters();
  $access_token = isset($get['access_token']) ? $get['access_token'] : FALSE;

  $result = $access_token !== FALSE ? odp_api_get_user_by_key($access_token) : FALSE;

  return $result;
}
