<?php
/**
 * @file
 * Main file for the GB Extra Fields module.
 */

/**
 * Implements hook_node_view().
 */
function gb_extra_fields_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'dataset') {
    $node->content['dataset_title'] = array(
      '#type' => 'markup',
      '#theme' => 'gb_extra_fields_dataset_title',
      '#node' => $node,
      '#title' => t('Dataset name'),
    );
    $node->content['dataset_resource_data_url'] = array(
      '#type' => 'markup',
      '#theme' => 'gb_extra_fields_dataset_resource_data_url',
      '#node' => $node,
      '#title' => t('Data URL'),
    );
    $node->content['dataset_resource_data_format'] = array(
      '#type' => 'markup',
      '#theme' => 'gb_extra_fields_dataset_resource_data_format',
      '#node' => $node,
      '#title' => t('Data format'),
    );
    $node->content['dataset_resource_structure_url'] = array(
      '#type' => 'markup',
      '#theme' => 'gb_extra_fields_dataset_resource_structure_url',
      '#node' => $node,
      '#title' => t('Structure URL'),
    );
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function gb_extra_fields_field_extra_fields() {
  $extra['node']['dataset'] = array(
    'display' => array(
      'dataset_title' => array(
        'label' => t('Dataset name'),
        'description' => t('Shows title of this dataset as a field.'),
        'weight' => 0,
      ),
      'dataset_resource_data_url' => array(
        'label' => t('Data URL'),
        'description' => t('Shows resource data URL as a field.'),
        'weight' => 0,
      ),
      'dataset_resource_data_format' => array(
        'label' => t('Data format'),
        'description' => t('Shows resource data format as a field.'),
        'weight' => 0,
      ),
      'dataset_resource_structure_url' => array(
        'label' => t('Structure URL'),
        'description' => t('Shows resource structure URL as a field.'),
        'weight' => 0,
      ),
    ),
  );

  return $extra;
}

/**
 * Implements hook_theme().
 */
function gb_extra_fields_theme($existing, $type, $theme, $path) {
  $theme = array(
    'gb_extra_fields_dataset_title' => array(
      'variables' => array('node' => NULL),
      'file' => 'gb_extra_fields.theme.inc',
    ),
    'gb_extra_fields_dataset_resource_data_url' => array(
      'variables' => array('node' => NULL),
      'file' => 'gb_extra_fields.theme.inc',
    ),
    'gb_extra_fields_dataset_resource_data_format' => array(
      'variables' => array('node' => NULL),
      'file' => 'gb_extra_fields.theme.inc',
    ),
    'gb_extra_fields_dataset_resource_structure_url' => array(
      'variables' => array('node' => NULL),
      'file' => 'gb_extra_fields.theme.inc',
    ),
  );

  return $theme;
}
