<?php
/**
 * @file
 * Main file for the GB Extra Fields module.
 */

/**
 * Implements hook_node_view().
 */
function gb_extra_fields_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'dataset') {
    $node->content['dataset_name'] = array(
      '#type' => 'markup',
      '#theme' => 'gb_extra_fields_dataset_name',
      '#node' => $node,
      '#enabled' => TRUE,
      '#title' => t('Dataset name'),
      '#view_mode' => $view_mode,
    );
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function gb_extra_fields_field_extra_fields() {
  $extra['node']['dataset'] = array(
    'display' => array(
      'dataset_name' => array(
        'label' => t('Dataset name'),
        'description' => t('Shows title of this dataset as a field.'),
        'weight' => 0,
      ),
    ),
  );

  return $extra;
}

/**
 * Implements hook_theme().
 */
function gb_extra_fields_theme($existing, $type, $theme, $path) {
  $theme = array(
    'gb_extra_fields_dataset_name' => array(
      'variables' => array('node' => NULL),
      'file' => 'gb_extra_fields.theme.inc',
    ),
  );

  return $theme;
}
