<?php
/**
 * @file
 * Theme functions for GB Extra Fields module.
 */

function theme_gb_extra_fields_dataset_title($vars) {
  return $vars['node']->title;
}

function theme_gb_extra_fields_dataset_resource_data_url($vars) {
  return $vars['node']->title;
}

function theme_gb_extra_fields_dataset_resource_data_format($vars) {
  return $vars['node']->title;
}

function theme_gb_extra_fields_dataset_resource_structure_url($vars) {
  return $vars['node']->title;
}
