<?php

define('CSV_DELIMETER', ',');
define('CSV_ENCLOSURE', chr(34)); // "
define('CRLF', chr(0x0d) . chr(0x0a));
define('DT_VOCAB', 'xsd');
define('OD_FILE_PREPROCESS_CONSTISTENCY_OK',            bindec('000001'));
define('OD_FILE_PREPROCESS_CONSTISTENCY_FAILURE',       bindec('000010'));
define('OD_FILE_PREPROCESS_CONSTISTENCY_WARNING',       bindec('000100'));
define('OD_FILE_PREPROCESS_CONSTISTENCY_SINGLE_FILE',   bindec('001000'));
define('OD_FILE_PREPROCESS_CONSTISTENCY_NO_STRUCTURE',  bindec('010000'));


/**
 *  Define file structure table headers
 */
function od_file_preprocess_structure_headers() {
  return array(
    '№',
    'Наименование поля',
    'Описание',
    'Формат значения поля',
  );
}

function od_file_preprocess_table_mimes() {
  return array(
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.oasis.opendocument.spreadsheet',
    'text/csv',
  );
}

function od_file_preprocess_graph_mimes() {
  return array(
    'application/xml',
  );
}


/**
 *  Define supported field types
 */
function od_file_preprocess_supporting_fieldtypes() {
  return array(
    'file',
    'recline_field',
  );
}


/**
 * Implements hook_form_alter()
 */
function od_file_preprocess_form_alter(&$form, &$form_state, $form_id) {

  // add preprocess checkbox into file field settings form
  if ($form_id == 'field_ui_field_edit_form' && in_array($form['#field']['type'], od_file_preprocess_supporting_fieldtypes())) {
    $form['instance']['settings']['od_file_preprocess'] = array(
      '#type' => 'checkbox',
      '#title' => t('Preprocess file with the open data'),
      '#default_value' => (isset($form['#instance']['settings']['od_file_preprocess'])) ? $form['#instance']['settings']['od_file_preprocess'] : FALSE,
      '#weight' => 20,
    );
  }
}


/**
 * Implements hook_field_widget_form_alter()
 */
function od_file_preprocess_field_widget_form_alter(&$element, &$form_state, $context) {
  // add preprocess and validate callbacks for widget 
  if (in_array($context['field']['type'], od_file_preprocess_supporting_fieldtypes()) && 
      isset($context['instance']['settings']['od_file_preprocess']) &&
      ($context['instance']['settings']['od_file_preprocess'])) {

    $js = drupal_get_path('module', 'od_file_preprocess') . '/' . 'od_file_preprocess.js';
    foreach ($element as &$el) {
      $el['#process'][] = 'od_file_preprocess_file_element_set_identity';
      $el['#process'][] = 'od_file_preprocess_widget_process';
      //$el['#element_validate'][] = 'od_file_preprocess_widget_validate';
      $el['#attached']['js'][] = $js;
      //$el['#after_build'][] = 'od_file_preprocess_file_element_after_build';

      //$el = od_file_preprocess_file_element_set_identity($el, $form_state);
      //$el = od_file_preprocess_widget_process($el, $form_state);
    }
  }
}

function od_file_preprocess_file_element_set_identity($element, &$form_state) {
  $element['upload_button']['#identity'] = 'upload_button';
  $element['remove_button']['#identity'] = 'remove_button';
  $element['errors'] = array(
    '#type' => 'container',
    '#weight' => -5000,
  );

  if (($fid = $element['#value']['fid']) != 0 && ($file = file_load($fid))) {
    switch($file->filemime) {
      case 'application/zip':
      case 'text/csv':
        $element['appropriate_options']['csv_parser']['delimiter'] = array(
          '#type' => 'select',
          '#title' => t('CSV Delimiter'),
          '#options' => array(
            ';' => t('Semicolon (;)'),
            ',' => t('Comma (,)'),
          ),
          '#identity' => 'delimiter_change',
          '#ajax' => $element['upload_button']['#ajax'],
          '#default_value' => ';',
        );
        break;
    }
  }

  //$element['appropriate_options']['#weight'] = -500;

  return $element;
}

/**
 * Process form file element
 */
function od_file_preprocess_widget_process($element, &$form_state) {
  if (empty($form_state['triggering_element'])) {
    return $element;
  }

  $field_name = $element['#field_name'];
  $lang = $element['#language'];
  $delta = $element['#delta'];

  $file_loaded = (isset($form_state['values'][$field_name][$lang][$delta]['fid']) &&
                  ($form_state['values'][$field_name][$lang][$delta]['fid']));

  $generate_structure = TRUE; //@todo: Replace with checking if checkbox is set or something.
  if (!$file_loaded) {
    return $element;
  }

  $file = $element['#file'];

  // Set shared options if needed
  $options = &$element['#value']['appropriate_options'];
  if (!empty($options) && is_array($options)) {
    foreach ($options as $_key => $_values) {
      foreach ($_values as $_property => $_value) {
        od_file_preprocess_options($_key, $_property, $_value);
      }
    }
  }

  // Check consistency of a file.
  $consistency = od_file_preprocess_check_structures($file, TRUE);

  if ($consistency & (OD_FILE_PREPROCESS_CONSTISTENCY_FAILURE | OD_FILE_PREPROCESS_CONSTISTENCY_WARNING)) {
    $element['errors']['consistency'] = array(
      '#markup' => t('There was an error in consistency'),
    );
  }


  $identity = isset($form_state['triggering_element']['#identity']) ? $form_state['triggering_element']['#identity'] : 'unknown';
  if ($identity == 'remove_button' || !$generate_structure) {
    //$element['file_data'] = null;
    $form_state['values'][$field_name][$lang][$delta]['file_data'] = null;
    $form_state['input'][$field_name][$lang][$delta]['file_data'] = null;
    $form_state['storage']['structure'] = null;
  }
  elseif ($generate_structure) {
    /*
     * @note: This will get this from static cache
     * cause od_file_preprocess_check_structures() above has called this function already.
     */
    $structures = od_file_preprocess_get_structure($file, TRUE, FALSE);

    // Get structure of the first element
    $structure = reset($structures);
    if (is_array($structure)) {
      $element['file_data']['#parents'] = array(
        $field_name,
        $lang,
        $delta,
        'file_data',
      );
      form_set_value($element['file_data'], $structure, $form_state);
    }

    module_load_include('rules.inc', 'od_file_process');
    $processed = od_file_process_rule_callback_get_files($element['#value'], TRUE);

    if (isset($form_state['values'][$field_name][$lang][$delta]['file_data'])) {
      $wrapper = 'edit-' . str_replace('_', '-', $field_name);
      $element['file_data'] = od_file_preprocess_set_element($form_state['values'][$field_name][$lang][$delta]['file_data'], $wrapper);
      $element['file_data']['#attributes'] = array(
        'class' => array('od-preprocess-filedata'),
      );
      $element['file_data']['#type'] = 'container';
//      $element['file_data']['#states'] = array(
//        'visible' => array(
//          '.field-name-field-dataset-convert input[value="1"]' => array(
//            'checked' => FALSE,
//          ),
//        ),
//      );
    }
  }

  return $element;
}


/**
 * Validate form file element
 * @fixme: Doesn't work at all
 */
function od_file_preprocess_widget_validate($element, &$form_state, $form) {
  return;
  if (!isset($form_state['input']['op']) || 
      $form_state['input']['op'] != 'Submit Form') {  
    return;
  }

  $field_name = $element['#field_name'];
  $lang = $element['#language'];
  $delta = $element['#delta'];

  $file_loaded = (isset($form_state['values'][$field_name][$lang][$delta]['fid']) &&
                  ($form_state['values'][$field_name][$lang][$delta]['fid']));
                  
  if (!$file_loaded) {
    if ($element['#required']) {
      form_error($element, t('The field %field is required. ', array('%field' => $element['#title'])));
    }
    return;
  }
  
  $col_data = isset($form_state['values'][$field_name][$lang][$delta]['file_data']['col_data']) ? 
                $form_state['values'][$field_name][$lang][$delta]['file_data']['col_data'] : NULL;

  if (!$col_data) {
    form_error($element, t('Can not parse file structure'));
  }
  else {
    foreach ($col_data as $row_id => $row) {
      if (!$row['col_name']['value']) {
        form_error($element['file_data']['col_data'][$row_id]['col_name'], 
                   t('Column %col name is empty', array('%col' => $row_id + 1)));
      }
      if ($row['datatype'] == 'undefined') {
        $col_name = ($row['col_name']['value']) ? 
                      '"' . $row['col_name']['value'] . '"' : 
                      t('#%col', array('%col' => $row_id + 1));
                      
        form_error($element['file_data']['col_data'][$row_id]['datatype'], 
                   t('Undefined data type for column %col', array('%col' => $col_name)));
      }
    }
  }
}


/**
 *  Parse file structure into $form_state-liked array
 * @todo Cache php_excel loaded things to prevent parsing it again
 */
function od_file_preprocess_get_structure($file, $process_2nd_row = FALSE, $index = 0) {
  $cache = &_od_file_preprocess_caches(__FUNCTION__);
  $cache_key = substr(md5($file->uri . $process_2nd_row . $index. filemtime($file->uri)), 0, 8);
  if (!isset($cache[$cache_key])) {
    // Lets think pessimistically and say that we won't get structure.
    $cache[$cache_key] = FALSE;

    od_file_process_prepare_playground();
    if (!is_object($file)) return NULL;
    $path = drupal_realpath($file->uri);

    switch ($file->filemime) {
      case 'application/vnd.ms-excel':                                          // .xls
      case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': // .xlsx
      case 'application/vnd.oasis.opendocument.spreadsheet':                    // .ods
      case 'text/csv':
      case 'application/zip':

          $structures = array(
            //'process_2nd_row' => $process_2nd_row,
          );

          if ($file->filemime == 'text/csv') {
            $data = od_file_preprocess_parse_csv($path);
          }
          elseif ($file->filemime == 'application/zip') {
            $data = od_file_preprocess_parse_zip($path);
          }
          else {
            module_load_include('inc', 'phpexcel');
            $data = od_file_preprocess_excel_import($path, FALSE);
          }

          od_file_preprocess_array_cleanup($data);
          if (empty($data)) return NULL;

          if (is_numeric($index)) {
            if (isset($data[$index])) {
              $data = array(
                $index => $data[$index],
              );
            }
            else {
              return FALSE;
            }
          }

          foreach ($data as $item_index => &$_data) {
            $_data = array_map('array_filter', $_data); //clear empty rows and cells
            $headers = array_shift($_data);

            //$col_types = array_fill(0, count($headers), 'undefined');
            $col_desc = ($process_2nd_row) ? NULL : array_shift($_data);

            $data_type_weight = array(
              'undefined' => 0,
              'integer' => 10,
              'float' => 20,
              'double' => 30,
              'anyURI' => 40,
              'string' => 50,
            );

            $col_types = array();
            $structure = array();
            foreach ($headers as $col => $header) {
              foreach ($data as $_list_index => &$_rows) {
                foreach ($_rows as $row) {
                  $cell = $row[$col];
                  if (!isset($col_types[$col])) {
                    $col_types[$col] = 'undefined';
                  }

                  if ($col_types[$col] == 'undefined') {
                    $col_types[$col] = od_file_preprocess_get_data_type($cell);
                  }
                  else {
                    $cell_type = od_file_preprocess_get_data_type($cell);
                    if ($data_type_weight[$cell_type] > $data_type_weight[$col_types[$col]]) {
                      $col_types[$col] = $cell_type;
                    }
                  }
                }
              }

              $structure['col_data'][$col]['col_name']['value'] = $header;
              $structure['col_data'][$col]['col_desc'] = ($col_desc) ? $col_desc[$col] : '';
              $structure['col_data'][$col]['datatype'] = $col_types[$col];

              $col++;
            }

            $structure['is_table_data'] = TRUE;
            $structures[$item_index] = $structure;
          }


          $cache[$cache_key] = $structures;
        break;
      default:
        $cache[$cache_key] = NULL; // No errors were occurred. Just there is no structure for this file type.
        break;
    }
  }

  $ret = &$cache[$cache_key];
  if (is_numeric($index)) {
    $ret = isset($ret[$index]) ? $ret[$index] : NULL;
  }

  return $ret;
}

function od_file_preprocess_check_structures($file, $process_second_row = FALSE) {
  $cache = &_od_file_preprocess_caches(__FUNCTION__);
  $cache_key = substr(md5($file->uri . $process_second_row), 0, 8);
  if (!isset($cache[$cache_key])) {
    $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_WARNING;
    if (($structures = od_file_preprocess_get_structure($file, $process_second_row, FALSE)) && count($structures) > 0) {
      $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_OK;
      $first = array_shift($structures);
      if (!empty($structures)) {
        $quality_control_hash = substr(md5(serialize($first)), 0, 32);
        foreach ($structures as $structure) {
          $hash = substr(md5(serialize($structure)), 0, 32);
          if ($hash != $quality_control_hash) {
            $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_FAILURE;
            break;
          }
        }
      }
      else {
        $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_SINGLE_FILE | OD_FILE_PREPROCESS_CONSTISTENCY_OK;
      }
    }
    elseif ($structures === NULL) {
      $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_NO_STRUCTURE;
    }
    elseif ($structures === FALSE) {
      $consistency = OD_FILE_PREPROCESS_CONSTISTENCY_FAILURE;
    }

    $cache[$cache_key] = $consistency;
  }

  return $cache[$cache_key];
}

/**
 * Create form element from $form_state values
 */
function od_file_preprocess_set_element($values = array(), $wrapper = '') {

  if (!count($values)) return FALSE;
/*
  $element['process_2nd_row'] = array(
    '#type' => 'checkbox',
    '#default_value' => (isset($values['process_2nd_row']) && $values['process_2nd_row']),
    '#title' => t('Second row not contain columns descriptions'),
    '#ajax' => array(
      'callback' => 'od_file_preprocess_ajax_callback',
      'wrapper' => $wrapper,
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
*/
//  if (!empty($values['codepage'])) {
//    $element['codepage'] = array(
//      '#type' => 'select',
//      '#title' => t('Code page of loaded document'),
//      '#options' => array(
//        'CP1251' => 'cp-1251 (Windows)',
//        'UTF-8' => 'utf-8 (Unicode)',
//      ),
//      '#ajax' => array(
//        'callback' => 'od_file_preprocess_ajax_callback',
//        'wrapper' => $wrapper,
//        'method' => 'replace',
//        'effect' => 'fade',
//      ),
//      '#default_value' => $values['codepage'],
//    );
//  }

  if (!empty($values['is_table_data'])) {
    $element['convert_to'] = array(
      '#type' => 'select',
      '#title' => t('Save file as'),
      '#options' => array(
        'csv' => 'csv',
        'xml' => 'xml',
      ),
      '#default_value' => !empty($values['convert_to']) ?  $values['convert_to'] : 'csv',
    );
  }
  
  $element['col_data'] = array(
    '#type' => 'table',
    '#header' => od_file_preprocess_structure_headers(),
  );

  foreach ($values['col_data'] as $col => $value) {
    $element['col_data'][$col] = array(
      'rownum' => array(
        '#type' => 'markup',
        '#markup' => $col + 1,  // row numbering starts from 1
      ),
      'col_name' => array(
        '#type' => 'container', // non-editable element, values stored in $form_state
        'display' => array(
          '#type' => 'markup',
          '#markup' => $value['col_name']['value'],
        ),
        'value' => array(
          '#type' => 'hidden',
          '#value' => $value['col_name']['value'],
        ),
      ),      
      'col_desc' => array(
        '#type' => 'textarea',
        '#size' => 10,
        '#required' => FALSE,
        '#cols' => 40,
        '#rows' => 3,
        '#resizable' => FALSE,
        '#value' => $value['col_desc'],
      ),
      'datatype' => array(
        '#type' => 'select',
        '#options' => array(
          'undefined' => t('Undefined'),
          'boolean' => t('Boolean'),
          'integer' => t('Integer'),
          'double' => t('Double'),
          'dateTime' => t('dateTime'),
          'anyURI' => t('anyURI'),
          'string' => t('String'),
        ),
        '#value' => $value['datatype'],
        '#attributes' => array('class' => array('od-preprocess-datatype-selector')),
        '#required' => FALSE,
      ),
    );
    if (empty($element['col_data'][$col]['col_name']['display']['#markup'])) {
      $element['col_data'][$col]['col_name']['display']['#markup'] = t('Column name can not be empty');
      $element['col_data'][$col]['col_name']['display']['#prefix'] = '<div class ="messages error">';
      $element['col_data'][$col]['col_name']['display']['#suffix'] = '</div>';
    }
  }
  return $element;
}


/**
 *  ajax callback for 'parse_2nd_row' form element 
 */

function od_file_preprocess_ajax_callback($form, $form_state) {
  return $form[$form_state['triggering_element']['#parents'][0]];
}


/**
 * trying to guess data type
 */
function od_file_preprocess_get_data_type($val) {

  if (empty($val) && $val !== 0) return 'undefined';
  
  if (is_numeric($val)) {

    if ((int)$val == $val || $val === 0) {
      return 'integer';
    }
    else {
      return 'double';
    }
  }
  else {
    if (valid_email_address($val) || valid_url($val, TRUE)) {
      return 'anyURI';
    }
    else {
      return 'string';
    }
  }
}

/**
 * @param $path
 * @param bool $codepage
 * @return array
 */
function od_file_preprocess_parse_csv($path, $codepage = FALSE) {
  $cache = &_od_file_preprocess_caches(__FUNCTION__);
  $cache_key = substr(md5($path), 0, 8);
  if (!isset($cache[$cache_key])) {
    include_once DRUPAL_ROOT . '/sites/all/libraries/PHPExcel/Classes/PHPExcel.php';
    include_once DRUPAL_ROOT . '/sites/all/libraries/PHPExcel/Classes/PHPExcel/IOFactory.php';

    if (!$codepage && FALSE === ($codepage = od_detect_encoding_guess_file($path))) {
      // If we couldn't guess encoding automatically, fallback it to UTF8
      $codepage = ODDetectEncoding::ENC_UTF8;
    }

    $codepage = strtoupper($codepage);

    $objReader = new PHPExcel_Reader_CSV();
    $objReader->setReadDataOnly(TRUE);
    //default MS Excell - created csv settings
    $objReader->setInputEncoding($codepage);
    $objReader->setDelimiter(od_file_preprocess_options('csv_parser', 'delimiter', NULL, FALSE, ';'));

    $objPHPExcel = $objReader->load($path);
    $objWorksheet = $objPHPExcel->getActiveSheet();

    $row_n = 0;
    $data = array();
    foreach ($objWorksheet->getRowIterator() as $row) {
      $col_n = 0;
      $cellIterator = $row->getCellIterator();
      $cellIterator->setIterateOnlyExistingCells(false);
      foreach ($cellIterator as $cell) {
        $data[0][$row_n][$col_n] = $cell->getValue();
        $col_n++;
      }
      $row_n++;
    }

    $cache[$cache_key] = $data;
  }

  return $cache[$cache_key];
}

/**
 * @param null $key
 * @param array $default
 * @return mixed
 * @todo Turn to drupalcache, not static
 */
function &_od_file_preprocess_caches($key = NULL, $default = array(), $reset = FALSE) {
  $cache = &drupal_static(__FUNCTION__, array());
  if  ($key != NULL) {
    if ($reset || !isset($cache[$key])) {
      $cache[$key] = $default;
    }

    return $cache[$key];
  }

  if ($reset) {
    $cache = $default;
  }

  return $cache;
}

/**
 * Manipulates with shared od_file_preprocess module's options
 * @param string $key
 * @param string $name
 * @param mixed $value
 * @param bool $remove
 * @param mixed $default
 * @return mixed|null
 */
function od_file_preprocess_options($key = 'global', $name = NULL, $value = NULL, $remove = FALSE, $default = NULL) {
  static $key_cache_dependencies = array(
    'csv_parser' => array('od_file_preprocess_parse_csv', 'od_file_preprocess_get_structure'),
  );

  od_common_module('core');
  $defaults = array();
  $cache = &_od_file_preprocess_caches(__FUNCTION__, $defaults);
  $storage = &$cache[$key];
  if (_od_common_param_value_manipulation($storage, $name, $value) === NULL && $default !== NULL) {
    _od_common_param_value_manipulation($storage, $name, $default);
  }

  // If writing happens
  if (($remove || $value !== NULL) && isset($key_cache_dependencies[$key])) {
    foreach ($key_cache_dependencies[$key] as $_cid) {
      _od_file_preprocess_caches($_cid, NULL, TRUE);
    }
  }

  return _od_common_param_value_manipulation($storage, $name, $value, $remove);
}

/**
 * @param $path
 * @return array|bool
 * @todo Cache
 */
function od_file_preprocess_parse_zip($path) {
  $cache = &_od_file_preprocess_caches(__FUNCTION__);
  $cache_key = substr(md5($path), 0, 8);
  if (!isset($cache[$cache_key])) {
    $zip = new ZipArchive();
    if ($zip->open($path) != TRUE) {
      return FALSE; // An error was ocurred
    }

    od_common_module('core');
    $temp_dir = od_common_tmpfilename('temporary://', $path);
    mkdir($temp_dir);
    $zip->extractTo($temp_dir);
    $zip->close();

    od_common_module('core');
    if (!($files_list = od_common_list_dir($temp_dir))) {
      return FALSE;
    }

    $data = array();
    foreach ($files_list->raw as $fileinfo) {
      switch ($fileinfo['extension']) {
        case 'csv':
          $processed = od_file_preprocess_parse_csv($fileinfo['uri'], FALSE);
          if (is_array($processed)) {
            $data = array_merge($data, $processed);
          }
          break;
      }
    }

    $cache[$cache_key] = !empty($data) ? $data : FALSE;
    $data = NULL;
    $processed = NULL;
  }

  return $cache[$cache_key];
}

/**
 * Same as phpexcel_import but with short time caching.
 * @param $path
 * @param bool $keyed_by_headers
 * @param bool $keyed_by_worksheet
 * @param null $custom_calls
 * @return array|bool|PHPEXCEL_ERROR_FILE_NOT_READABLE|PHPEXCEL_ERROR_LIBRARY_NOT_FOUND
 * @todo Use _od_file_preprocess_caches()
 */
function od_file_preprocess_excel_import($path, $keyed_by_headers = TRUE, $keyed_by_worksheet = FALSE, $custom_calls = NULL) {
  static $cache_default = array(
    'bin' => 'cache',
    'data' => null,
  );

  $cid = substr(md5(implode('_', func_get_args())), 0, 8);
  static $cache = NULL;
  if (!$cache || FALSE === ($cache = cache_get($cid, $cache_default['bin']))) {
    $cache = (object) $cache_default;
    $cache->cid = $cid;
    $cache->expire = strtotime('+10 minutes');
  }

  $cache->bin = $cache_default['bin'];

  if (!isset($cache->data)) {
    $cache->data = phpexcel_import($path, $keyed_by_headers, $keyed_by_worksheet, $custom_calls);
    $cache->data = $cache->data ? $cache->data : FALSE;
    od_file_preprocess_array_cleanup($cache->data);

    cache_set($cache->cid, $cache->data, $cache->bin, $cache->expire);
  }

  return $cache->data;
}

function od_file_preprocess_array_cleanup(&$data) {
  if (!$data) return array();

  $data = array_map(function($arr) {
    $arr = array_map('array_filter', $arr);
    return array_filter($arr);
  }, $data);

  $data = array_filter($data);

  return $data;
}
