<?php

function od_display_passport_menu() {
  $items['getpassport/%'] = array(
    'page callback' => 'od_display_passport_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  return $items;
}

function od_display_passport_view($nid) {
  $data = NULL;
  print $nid;
  if (!empty($nid) && is_numeric($nid)) {
    $view = views_get_view('dataset');
    $view->set_display('passport_dataset');
    $view->set_arguments(array($nid));
    $view->execute();
    $data = $view->render();
    //$data = filter_xss($view->render(), array('a', 'p', 'span', 'table', 'thead', 'tbody', 'th', 'tr', 'td'));
  }
  print $data;
}