<?php

function od_display_passport_menu() {
  $items['getpassport/%'] = array(
    'page callback' => 'od_display_passport_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  return $items;
}

function od_display_passport_view($nid) {
  module_load_include('inc', 'od_passport', 'plugins/content_types/od_passport_pane');
  $data = drupal_render(od_passport_render($nid)->content);
  print "<form>
    <p><b>Скопируйте html-код паспорта:</b></p>
    <p><textarea rows='100' cols='120
    ' name='text' value='$data'></textarea></p>
  </form>";
}

