<?php

/**
 * Implements hook_libraries_info().
 */
function od_api_libraries_info() {
  // Init output variable.
  $items = array();

  $items['od_api'] = array(
    'name' => 'Opendata API',
    'dependencies' => array('easyrdf', 'idna'),
    'version' => '1.0',
    'files' => array(
      'php' => array(
        'odApi.php',
      ),
    ),
  );

  return $items;
}

/**
 * Invokes Opendata API library.
 */
function od_api() {
  $library = libraries_load('od_api');

  // Try to load the library and check if that worked.
  if (($library) && !empty($library['loaded'])) {
    return TRUE;
  }

  return FALSE;
}
