<?php

/**
 * Implements hook_menu().
 */
function op_api_menu() {
  // Init output variable.
  $items = array();

  $items['api'] = array(
    'title' => 'Example Page',
    'page callback' => 'op_api_api_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'delivery callback' => 'op_api_json_output',
  );

  return $items;
}

function op_api_json_output($var) {
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');

  if (isset($var)) {
    echo op_api_pretty_json_encode($var);
  }
}

function op_api_api_page() {
  $od_api_params = array(
    'args' => func_get_args(),
    'query' => array(),
  );

  $rdf = new OdApi($od_api_params);
  $rdf->parse();
  $rdf->execute();
  $output = $rdf->getResult();

  return $output;
}

function op_api_pretty_json_encode($var, $indent = 0, $tab = '  ') {
  $_myself = __FUNCTION__;
  $_escape = function($str) {
    return preg_replace("!([\b\t\n\r\f\"\\'])!", "\\\\\\1", $str);
  };

  $output = '';

  if (is_array($var) || is_object($var)) {
    if (is_array($var)) {
      $is_object = FALSE;
      $index = 0;
      foreach ($var as $key => $value) {
        if ($key !== $index) {
          $is_object = TRUE;
          break;
        }
        $index++;
      }
    }
    else {
      $is_object = TRUE;
    }

    if (is_object($var)) {
      $var = (array) $var;
    }

    $output .= $is_object ? '{' : '[';
    $inner_output = '';
    foreach ($var as $key => $value) {
      $inner_output .= str_repeat($tab, $indent + 1);
      if ($is_object) {
        $inner_output .=  "\"" . (is_string($key) ? $_escape($key) : $key) . "\"" . ': ';
      }
      $inner_output .= $_myself($value, $indent + 1) . ",\n";
    }
    if ($inner_output) {
      $inner_output = substr($inner_output, 0, -2);
      $output .= "\n" . $inner_output . "\n" . str_repeat($tab, $indent);
    }
    $output .= $is_object ? '}' : ']';
  }
  elseif (is_bool($var)) {
    $output .= $var ? 'true' : 'false';
  }
  elseif (is_null($var)) {
    $output .= 'null';
  }
  elseif (is_string($var)) {
    $output .= "\"" . $_escape($var) . "\"";
  }
  else {
    $output .= $var;
  }

  return $output;
}
