<?php

/**
 * Implements hook_init().
 */
function opendata_review_menu() {
  // Init variables.
  $items = array();

  $items['opendata-review'] = array(
    'title' => 'Проверка открытых данных',
    'page callback' => 'opendata_review_page_opendata_review',
    'access callback' => TRUE,
    'file' => 'includes/pages/opendata_review.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
