<?php

function piwik_report_dataselect_filtering_form_alter(&$form, &$form_state, $form_id){

    if ($form_id == 'piwik_reports_dateselect_form') {
        drupal_add_js( insert_javascript_str() , 'inline');


        $form['basic']['inline']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Filter'),
            '#weight' => 15,
            '#attributes' => array(
                'onclick' => 'this.form.action=this.form.action + tabPart()'
            )
        );

        //$form['actions']['submit']['#attributes']['onclick'] = 'this.form.action=this.form.action + tabPart()';
    }

}

function insert_javascript_str(){
    return "function tabPart(){
                elem = jQuery( \"li:first[class*='ui-tabs-selected ui-state-active']\" );
                a_tag_href_value = elem[0].childNodes[0].attributes['href'].nodeValue;
                return a_tag_href_value;
            }";
}