<?php

/**
 * Implements hook_element_info_alter().
 */
function hide_format_tips_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    $type['text_format']['#after_build'][] = 'hide_format_tips_after_build';
  }
}

function hide_format_tips_after_build($element, &$form_state) {
  if (isset($element['format']['guidelines'])) {
    $element['format']['guidelines']['#access'] = FALSE;
  }
  if (isset($element['format']['help'])) {
    $element['format']['help']['#access'] = FALSE;
  }
  if ((isset($element['format']['format']['#access'])) && ($element['format']['format']['#access'] === FALSE)) {
    $element['format']['#access'] = FALSE;
  }
  return $element;
}
