<?php

function custom_bef_sort_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['sort_bef_combine']['#options']) && count($form['sort_bef_combine']['#options'])) {
    $rewrite = (isset($form_state['exposed_form_plugin']->options['bef']['sort']['advanced']['combine_rewrite'])) ?
                $form_state['exposed_form_plugin']->options['bef']['sort']['advanced']['combine_rewrite'] : NULL;
    $rewrites = explode("\n", $rewrite);
    $options = $form['sort_bef_combine']['#options'];
    $sort = array();

    foreach ($rewrites as $veight => $rewrite) {
      $caption = str_replace('|', '', strstr($rewrite,'|'));
      if ($caption) {
        foreach ($options as $key => $option) {
          if ($option == $caption) {
            $sort[$key] = $option;
          }
        }
      }
    }

    if ($sort) $form['sort_bef_combine']['#options'] = $sort;
  }
}

