<?php

/**
 * Implements hook_permission().
 */
function view_own_unpsh_content_permission() {
  $perms = array();

  foreach (node_permissions_get_configured_types() as $type) {
    $info = node_type_get_type($type);
    $perms += array(
      "view own unpublished $type content" => array(
        'title' => t('%type_name: View own unpublished content', array('%type_name' => $info->name)),
      ),
      "view all unpublished $type content" => array(
        'title' => t('%type_name: View all unpublished content', array('%type_name' => $info->name)),
      )
    );
  }

  return $perms;
}

/**
 * Implements hook_node_access().
 */
function view_own_unpsh_content_node_access($node, $op, $account) {
  if (is_object($node) && ($op == 'view')) {
    if (user_access('view all unpublished ' . $node->type . ' content', $account)) {
      return NODE_ACCESS_ALLOW;
    }
    elseif ($node->status == 0 && $account->uid == $node->uid) {
      if (in_array($node->type, node_permissions_get_configured_types())) {
        if (user_access('view own unpublished ' . $node->type . ' content', $account)) {
          return NODE_ACCESS_ALLOW;
        }
      }
    }
  }

  return NODE_ACCESS_IGNORE;
}
