<?php

/**
 * Import user ID.
 */
define('OD_COMMON_IMPORT_USER_ID', 107);

/**
 * Dataset fields.
 */
define('OD_COMMON_FIELD_DATASET_IDENTIFIER', 'field_dataset_id');
define('OD_COMMON_FIELD_DATASET_DESCRIPTION', 'body');
define('OD_COMMON_FIELD_DATASET_OWNER', 'field_organization');
define('OD_COMMON_FIELD_DATASET_CREATED', 'field_date_first_time_publ');
define('OD_COMMON_FIELD_DATASET_UPDATED', 'field_date_last_change');
define('OD_COMMON_FIELD_DATASET_PROVENANCE', 'field_content_last_change');
define('OD_COMMON_FIELD_DATASET_SUBJECT', 'field_tags');
define('OD_COMMON_FIELD_DATASET_RESOURCES', 'field_resources');

/**
 * Dataset publisher fields.
 */
define('OD_COMMON_FIELD_DATASET_PUBLISHER_NAME', 'field_contact_name');
define('OD_COMMON_FIELD_DATASET_PUBLISHER_PHONE', 'field_contact_phone');
define('OD_COMMON_FIELD_DATASET_PUBLISHER_EMAIL', 'field_email_responsible');

/**
 * Resource fields.
 */
define('OD_COMMON_FIELD_RESOURCE_DATASET', 'field_dataset_ref');
define('OD_COMMON_FIELD_RESOURCE_CREATED', 'field_created');
define('OD_COMMON_FIELD_RESOURCE_PROVENANCE', 'field_provenance');
define('OD_COMMON_FIELD_RESOURCE_FORMAT', 'field_format');
define('OD_COMMON_FIELD_RESOURCE_DATA', 'field_upload');
define('OD_COMMON_FIELD_RESOURCE_CSV_DELIMITER', 'field_csv_delimiter');
define('OD_COMMON_FIELD_RESOURCE_ENCODING', 'field_encoding');
define('OD_COMMON_FIELD_RESOURCE_STRUCTURE', 'field_upload_structure');
