<?php

/**
 * Define max opendata file size.
 */
define('OD_IMPORT_OPENDATA_MAX_SIZE', 30 * 1024 * 1024);

/**
 * Opendata API object types.
 */
define('OD_IMPORT_DATA_TYPE', 'data');
define('OD_IMPORT_STRUCTURE_TYPE', 'structure');

/**
 * Taxonomy vocabularies.
 */
define('OD_IMPORT_VOCABULARY_FORMATS', 'format');
define('OD_IMPORT_VOCABULARY_FORMATS_ID', 1);
define('OD_IMPORT_VOCABULARY_SUBJECTS', 'tags');
define('OD_IMPORT_VOCABULARY_SUBJECTS_ID', 2);
