<?php

/**
 * Implements hook_menu().
 */
function od_form_custom_validation_menu() {
  $items = array();
  $items['od_form_custom_validation_ajax'] = array(
    'page callback' => 'od_form_custom_validation_ajax_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'delivery callback' => 'ajax_deliver',
    'theme callback' => 'ajax_base_page_theme',
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function od_form_custom_validation_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'od_preprocess_wizard_entityform_edit_form') {
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'od_form_custom_validation') . '/od_form_custom_validation.js',
    );
    $form['messages'] = array(
      '#markup' => '<div id="ajax-forms-messages"></div>',
      '#weight' => -50,
    );

    $form['actions']['submit']['#ajax'] = array(
      'path' => 'od_form_custom_validation_ajax',
    );
  }
}

function od_form_custom_validation_ajax_callback() {
  module_load_include('pages.inc', 'entityform');
  list($form, $form_state) = ajax_get_form();
  drupal_process_form($form['#form_id'], $form, $form_state);
  $commands = array();
  $commands[] = ajax_command_html('#ajax-forms-messages', theme('status_messages'));
  return array('#type' => 'ajax', '#commands' => $commands);
}
