<?php
/*
 * @file
 */

/**
 * Implements hook_preprocess_html()
 */
function od_cell_popup_preprocess_html(&$vars) {
  if (
    arg(0) == 'node'
      &&
    ($nid = arg(1)) && is_numeric($nid)
      &&
    ($node = node_load($nid)) && $node->type == 'resource'
  ) {
    drupal_add_library('od_common', 'jquery.tiptip');
    drupal_add_js(drupal_get_path('module', 'od_cell_popup'). '/js/popup.js');
    drupal_add_js(array(
      'od_cell_popup' => array(
        'popup' => array(
          'nid' => $nid,
        ),
      ),
    ), array('type' => 'setting'));
  }
}

/**
 * Implements hook_field_widget_form_alter()
 */
function od_cell_popup_field_widget_form_alter(&$element, &$form_state, $context) {
  $prepopulate_fields = array(
    'field_ds_report_row' => TRUE,
    'field_ds_report_col' => TRUE,
    'field_ef_dataset_resources' => TRUE,
  );

  if (isset($context['field']['field_name']) && isset($prepopulate_fields[$context['field']['field_name']])) {
    $vc = NULL;
    switch ($context['field']['type']) {
      case 'entityreference':
        $vc = &$element['target_id'];
        break;
      default:
        $vc = &$element['value'];
    }

    if ($vc !== NULL) {
       $vc['#value_callback'] = 'od_cell_popup_prepopulate_field_from_uri';
    }

    if (empty($_GET['fields_debug'])) {
      $element['#access'] = FALSE;
    }
  }
}

function od_cell_popup_prepopulate_field_from_uri($element, $input, $form_state) {
  if (isset($_GET[$element['#field_name']])) {
    return $_GET[$element['#field_name']];
  }

  return $input;
}