<?php

/**
 * Define max opendata file size.
 */
define('ODP_IMPORT_OPENDATA_MAX_SIZE', 30 * 1024 * 1024);

/**
 * Opendata API object types.
 */
define('ODP_IMPORT_DATA_TYPE', 'data');
define('ODP_IMPORT_STRUCTURE_TYPE', 'structure');

/**
 * Taxonomy vocabularies.
 */
define('ODP_IMPORT_VOCABULARY_FORMATS', 'format');
define('ODP_IMPORT_VOCABULARY_FORMATS_ID', 1);
define('ODP_IMPORT_VOCABULARY_SUBJECTS', 'tags');
define('ODP_IMPORT_VOCABULARY_SUBJECTS_ID', 2);

/**
 * Define opendata import timer format.
 */
define('ODP_IMPORT_TIMER_FORMAT', 'Y-m-d H:i:s');
