<?php
/*
 * @file
 */

//function od_geocoder_rules_action_info() {
//  return array(
//    'od_dataset_create_new_revision' => array(
//      'label' => t('Create new revision of dataset (with resources)'),
//      'parameter' => array(
//        'node' => array(
//          'type' => 'node',
//          'label' => t('Node'),
//        ),
//      ),
//      'provides' => array(
//        'new_revision' => array(
//          'type' => 'node',
//          'label' => t('New revision node'),
//          'save' => TRUE,
//        ),
//      ),
//      'group' => t('Datasets'),
//      'base' => 'od_dataset_rules_actions_create_new_revision',
//    ),
//    'od_dataset_set_latest_update_time' => array(
//      'label' => t('Set dataset\'s latest update time'),
//      'parameter' => array(
//        'date_type' => array(
//          'type' => 'text',
//          'label' => t('Choose a date to change'),
//          'options list' => 'od_dataset_date_available_parts',
//        ),
//        'node' => array(
//          'type' => 'node',
//          'label' => t('Node'),
//        ),
//        'date_part' => array(
//          'type' => 'date',
//          'label' => t('Date part'),
//        ),
//        'time_part' => array(
//          'type' => 'date',
//          'label' => t('Time part'),
//          'optional' => TRUE,
//          'default value' => NULL,
//        ),
//      ),
//      'group' => t('Datasets'),
//      'base' => 'od_dataset_rules_actions_set_latest_update_time',
//    ),
//  );
//}

