<?php

/**
 * Define log importance types.
 */
define('OD_LOG_IMPORTANCE_STATUS', 'status');
define('OD_LOG_IMPORTANCE_WARNING', 'warning');
define('OD_LOG_IMPORTANCE_ERROR', 'error');

/**
 * Define log event types.
 */
define('OD_LOG_EVENT_DATASET_ADDED', 'dataset_added');
define('OD_LOG_EVENT_DATASET_CHANGED', 'dataset_changed');
define('OD_LOG_EVENT_RESOURCE_ADDED', 'resource_added');
define('OD_LOG_EVENT_RESOURCE_CHANGED', 'resource_changed');
define('OD_LOG_EVENT_RESOURCE_DELETED', 'resource_deleted');
define('OD_LOG_EVENT_IMPORT_DATA', 'import_data');
