<?php
/*
 * @file
 */

function od_detect_encoding_guess_string() {
  return od_detect_encoding_get_detector()->guessEncoding('Tratatatata!');
}

/**
 * @return ODDetectEncoding
 */
function od_detect_encoding_get_detector() {
  static $instance = NULL;
  if ($instance === NULL) {
    $adapter = new ODDetectEncodingAdapter_Enca();
    $instance = new ODDetectEncoding($adapter);
  }

  return $instance;
}