<?php
/**
 * @file
 * Defines a Field none storage backend.
 */

/**
 * Implements hook_field_storage_info().
 */
function field_none_storage_field_storage_info() {
  return array(
    'field_none_storage' => array(
      'label' => t('Field none storage'),
      'description' => t('Dummy storage backend. Allow create fields which don\' store any data.'),
    ),   
  );
}

/**
 * Implements hook_field_storage_details().
 */
function field_none_storage_field_storage_details($field) {  
  return array();
}

/**
 * Implements hook_field_storage_load().
 */
function field_none_storage_field_storage_load($entity_type, $entities, $age, $fields, $options) {}

/**
 * Implements hook_field_storage_write().
 */
function field_none_storage_field_storage_write($entity_type, $entity, $op, $fields) {}

/**
 * Implements hook_field_storage_delete().
 */
function field_none_storage_field_storage_delete($entity_type, $entity, $fields) {}

/**
 * Implements hook_field_storage_purge().
 */
function field_none_storage_field_storage_purge($entity_type, $entity, $field, $instance) {}

/**
 * Implements hook_field_storage_delete_revision().
 */
function field_none_storage_field_storage_delete_revision($entity_type, $entity, $fields) {}

/**
 * Implements hook_field_storage_create_field().
 */
function field_none_storage_field_storage_create_field($field) {}

/**
 * Implements hook_field_storage_delete_field().
 */
function field_none_storage_field_storage_delete_field($field) {}

/**
 * Implements hook_field_storage_delete_instance().
 */
function field_none_storage_field_storage_delete_instance($instance) {}

/**
 * Implements hook_field_attach_create_bundle().
 */
function field_none_storage_field_attach_create_bundle($bundle) {}

/**
 * Implements hook_field_attach_rename_bundle().
 */
function field_none_storage_field_attach_rename_bundle($bundle_old, $bundle_new) {}

/**
 * Implements hook_field_attach_delete_bundle().
 */
function field_none_storage_field_attach_delete_bundle($entity_type, $bundle, $instances) {}

/**
 * Implements hook_field_storage_query().
 */
function field_none_storage_field_storage_query(EntityFieldQuery $query) {}
