<?php

/**
 * Include API files.
 */
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'op_core') . '/' . 'includes/controller.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'op_core') . '/' . 'includes/view.inc';

/**
 * Implements hook_theme().
 */
function op_core_theme() {
  // Init return variable.
  $items = array();

  $items['op_opendata_list_in_textarea'] = array(
    'variables' => array('user' => NULL),
  );
  $items['op_opendata_meta_in_textarea'] = array(
    'variables' => array('node' => NULL),
  );

  $items['op_render_in_textarea'] = array(
    'variables' => array('html' => NULL),
  );

  return $items;
}

function op_core_node_view($node, $view_mode, $langcode) {
  // kpr($node);
}

function op_core_views_post_execute(&$view) {
  $view_name = $view->name;
  $view_display = $view->current_display;

  if ($view_name === 'user_opendata_list' && $view_display === 'view') {
    $result = $view->result;
    $nids = op_core_get_views_result_nids($result);

    $nodes = node_load_multiple($nids);

    if (empty($nodes)) {
      return;
    }

    $opendata_urls = array();
    foreach ($nodes as $node) {
      $node_opendata = new Opendata($node);

      $opendata_urls['/' . $node_opendata->get_uri()] = '/' . 'node/' . $node->nid;
    }

    drupal_add_js(array('opCoreOpendataList' => $opendata_urls), 'setting');
    drupal_add_js(drupal_get_path('module', 'op_core') . '/' . 'includes/js/op_core.js');
  }
}
