<?php

/**
 * @file
 * A collection of validators that provide more function for Field Validation.
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function custom_field_validation_ctools_plugin_directory($module, $plugin) {
  if ($module == 'field_validation' && $plugin == 'validator') {
    return 'plugins/' . $plugin;
  }
}

function custom_field_validation_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form['#entity_type']) && isset($form['#bundle'])) {
    ctools_include('export');
    $params = array(
      'entity_type' => $form['#entity_type'], 
      'bundle' => $form['#bundle']
    );
    $rules = ctools_export_load_object('field_validation_rule', 'conditions', $params);
    foreach ($rules as $rule) {
      //Disabled by Ctools.
      if (!empty($rule->disabled)) {
        continue;
      }
      if ($rule->validator == 'field_validation_required_fields_by_field_validator') {
        if (!isset($form[$rule->field_name])) {
          continue;
        }
        
        $script = drupal_get_path('module', 'custom_field_validation') . '/custom_field_validation.js';
        
        if (!isset($form['#attached']['js']) || 
            !is_array($form['#attached']['js']) || 
            !in_array($script, $form['#attached']['js'])) 
          $form['#attached']['js'][] = $script;
          
        if (arg(0) == 'user' && arg(2) == 'edit') {
          $form[$rule->field_name]['#attributes']['style'][] = 'display:none;'; // <--- TODO
        }
        
        $lang = $form[$rule->field_name]['#language'];
        $field_name = str_replace('_', '-', $rule->field_name) . '-' . $lang;
        $type = $form[$rule->field_name][$lang]['#type'];
        $this_field = field_info_field($rule->field_name);
        $values = array_keys($this_field['settings']['allowed_values']);
        $visible = (isset($rule->settings['validation_fields_visible'])) ? $rule->settings['validation_fields_visible'] : array();

        $form[$rule->field_name]['#attributes']['class'][] = 'validation-requiring-element';
        
        foreach ($values as $value) {
          $name = 'validation_fields_require_' . $value;
          $required = (isset($rule->settings[$name])) ? $rule->settings[$name] : array();
          foreach ($required as $item) {
            if (isset($form[$item])) {
              $class = 'validation-edit-' . $field_name . '-' . $value;
              $form[$item]['#attributes']['class'][] = $class;
              //$form[$item]['#required'] = FALSE;
            }
          }
          $name = 'validation_fields_visible_' . $value;
          $visible = (isset($rule->settings[$name])) ? $rule->settings[$name] : array();
          foreach ($visible as $item) {
            if (isset($form[$item])) {
              $class = 'visible-edit-' . $field_name . '-' . $value;
              $form[$item]['#attributes']['class'][] = $class;
            }
          } 
        }
      }
    }
  }
}

