<?php
/**
 * @file
 *  Ajax facets implementation.
 */

/**
 * Implements hook_facetapi_widgets().
 */
function od_facets_facetapi_widgets() {
  $items = array();

  $items['od_facetapi_ajax_links'] = array(
    'handler' => array(
      'label' => 'Opendata Widget Checkboxes',
      'class' => 'FacetapiOdFacetsAjaxWidgetLinks',
      'query types' => array('term'),
    ),
  );

  return $items;
}
